framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    trusted_hosts:   ~
    fragments: ~
    http_method_override: true
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 2592000
        gc_maxlifetime: 2592000
    php_errors:
        log: true
    test: true
