members_parse:
    path:     /customer-upload
    defaults: { _controller: App\Controller\Customer\CustomerController::parse }
    methods:  [GET, POST]

members_file_count:
    path:     /file-count
    defaults: { _controller: App\Controller\Customer\CustomerController::countFileRows }
    methods:  POST

member_check_email:
    path:     /email-check
    defaults: { _controller: App\Controller\Customer\CustomerController::checkEmail }
    methods:  POST

customer_search:
    path:     /customer-find
    defaults: { _controller: App\Controller\Customer\CustomerController::searchCustomers }
    methods:  POST
    options:
          expose: true

customers_list:
    prefix:   /
    resource: list.yml

customers_emails:
    prefix:   /emails
    resource: email.yml
