member.email.auto:
    path:     /auto-emails
    defaults: { _controller: App\Controller\Customer\MailController::autoEmails }
    methods:  [GET, POST]

member.email.compose:
    path:     /compose-email/{id}
    defaults: { _controller: App\Controller\Customer\MailController::compose, id: null }
    methods:  [GET, POST]

member.email.customers.load:
    path:     /compose/recipients/load/{page}/{id}
    defaults: { _controller: App\Controller\Customer\MailController::loadCustomers, id: null }
    methods:  POST
    options:
              expose: true

member.email.save_draft:
    path:     /draft/save/{id}
    defaults: { _controller: App\Controller\Customer\MailController::saveDraft, id: null}
    methods:  POST
    options:
              expose: true

member.email.sending:
    path:     /sending/{id}
    defaults: { _controller: App\Controller\Customer\MailController::sendingEmail, id: null}
    methods:  GET

ajax_email_delete:
    path:     /delete/{id}
    defaults: { _controller: App\Controller\Customer\MailController::ajaxDelete }
    methods:  DELETE

member.email.recipients_search:
    path:     /search/{searchBy}/{searchText}
    defaults: { _controller: App\Controller\Customer\MailController::searchRecipients, searchBy: 'all', searchText: ''}
    methods:  POST

member.email.log:
    path:     /email-logs
    defaults: { _controller: App\Controller\Customer\MailController::log }
    methods:  GET

member.email.draft:
    path:     /draft-emails
    defaults: { _controller: App\Controller\Customer\MailController::drafts }
    methods:  GET

member.email.details:
    path:     /log/{id}/details
    defaults: { _controller: App\Controller\Customer\MailController::details }
    methods:  GET

member.compose.sending_check:
    path:     /sending-check/{id}
    defaults: { _controller: App\Controller\Customer\MailController::checkSending }
    methods:  GET
    options:
          expose: true

member.email.sending_error:
    path: /sending-error/{id}
    defaults: { _controller: App\Controller\Customer\MailController::sendingError }
    methods:  GET