customer_list:
    path:     /customer-search
    defaults: { _controller: App\Controller\Customer\CustomerController::list }
    methods:  [GET, POST]

member_edit:
    path:     /{id}/edit
    defaults: { _controller: App\Controller\Customer\CustomerController::edit }
    methods:  [GET, POST]
    options:
            expose: true

member_add:
    path:     /customer-add
    defaults: { _controller: App\Controller\Customer\CustomerController::add }
    methods:  [GET, POST]

member_delete:
    path:     /{id}/delete
    defaults: { _controller: App\Controller\Customer\CustomerController::delete }
    methods:  DELETE

member_summary_search:
    path:     /search-summary
    defaults: { _controller: App\Controller\Customer\CustomerController::searchSummary }
    methods:  POST

customer_orders_search:
    path:     /search-orders
    defaults: { _controller: App\Controller\Customer\CustomerController::searchOrders }
    methods:  POST