customer_product_add:
    path:     /product-add/{category}/{isPos}
    defaults: { _controller: App\Controller\Customer\ProductController::add, category: null, isPos: false }
    methods:  [GET, POST]

customer_product_edit:
    path:     /edit/{id}
    defaults: { _controller: App\Controller\Customer\ProductController::edit }
    methods:  [GET, POST]

customer_product_delete:
    path:     /{id}/delete
    defaults: { _controller: App\Controller\Customer\ProductController::delete }
    methods:  DELETE

customer_products_search:
    path:     /product-search/{category}/{searchText}
    defaults: { _controller: App\Controller\Customer\ProductController::search, category: 'all', searchText: '' }
    methods: [GET, POST]

products_pricing:
    path:     /product-pricing/{category}
    defaults: { _controller: App\Controller\Customer\ProductController::pricing, category: 'all' }
    methods:  [GET, POST]

product_pricing_send:
    path:     /pricing-send
    defaults: { _controller: App\Controller\Customer\ProductController::pricingSend }
    methods:  POST

products_search:
    path:     /products-search
    defaults: { _controller: App\Controller\Customer\ProductController::searchProducts }
    methods:  POST
    options:
              expose: true

product_price_update:
    path:     /product-price-update/{id}
    defaults: { _controller: App\Controller\Customer\ProductController::updatePrice }
    methods:  POST

product_update:
    path:     /product/{id}/update
    defaults: { _controller: App\Controller\Customer\ProductController::update }
    methods:  POST