member_share:
    path:     /
    defaults: { _controller: App\Controller\Customer\ShareController::addShare }
    methods:  [GET, POST]

ajax_member_share_update:
    path:     /update/{id}
    defaults: { _controller: App\Controller\Customer\ShareController::ajaxUpdateShare }
    methods:  POST

ajax_share_delete:
    path:     /delete/{id}
    defaults: { _controller: App\Controller\Customer\ShareController::ajaxDeleteShare }
    methods:  DELETE